name: terminal_hero
description: A gamified Linux learning app with terminal missions, XP, streaks, badges, and social sharing.
publish_to: "none"

version: 1.2.0+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  google_mobile_ads: ^8.0.0
  shared_preferences: ^2.4.23
  confetti: ^0.7.0
  share_plus: ^13.1.0
  google_fonts: ^8.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
